services:
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    network_mode: "host"
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - mongo

  cache:
    image: 'redis:alpine'
    command: redis-server
    restart: unless-stopped
    network_mode: 'host'

  video_processor:
    build: 
      context: .
      dockerfile: stream_events.Dockerfile
    command: sh -c "./stream_events"
    depends_on:
      - cache
    network_mode: 'host'
  
  backend:
    build: .
    command: poetry run uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
      - uploads:/app/uploads
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - cache
      - mongo
    network_mode: 'host'

  celery:
    build: .
    command: poetry run celery -A backend.worker worker -l info
    restart: unless-stopped
    volumes:
      - ./:/app
      - uploads:/app/uploads
    environment:
      - REDIS_HOST=redis://localhost:6379
    depends_on:
      - backend
      - mongo
    network_mode: 'host'

  load_balancer:
    image: nginx
    ports:
      - "443:443"
      - "444:444"
    volumes:
      - ./nginx/tiktok.conf:/etc/nginx/conf.d/tiktok.conf
      - ./nginx/moan.conf:/etc/nginx/conf.d/moan.conf
      - ./frontend/dist:/app/tiktok
      - ./ston_frontend/dist:/app/moan
      # - /etc/letsencrypt:/etc/letsencrypt/
    # depends_on:
    #   - backend
    network_mode: 'host'

networks:
  net:
    driver: bridge

volumes:
  uploads:
    driver: local
  mongo_data:
    driver: local