services:
  cache:
    container_name: cache_test
    image: 'redis:alpine'
    command: redis-server
    restart: unless-stopped
    networks:
      - net

  backend:
    container_name: backend_test
    build: .
    command: poetry run uvicorn backend.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app
      - uploads:/app/uploads
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis://cache:6379
    depends_on:
      - cache
    networks:
      - net

  celery:
    container_name: async_tasks
    build: .
    command: poetry run celery -A backend.worker worker -l info
    restart: unless-stopped
    volumes:
      - ./:/app
      - uploads:/app/uploads
    environment:
      - REDIS_HOST=redis://cache:6379
    depends_on:
      - backend
    networks:
      - net

  load_balancer:
    container_name: load_balancer_test
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist/:/app
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
    networks:
      - net


networks:
  net:
    driver: bridge

volumes:
  uploads:
